using SyncFactors.Domain;

namespace SyncFactors.Domain.Tests;

public sealed class SourceAttributePathNormalizerTests
{
    [Theory]
    [InlineData("personalInfoNav[0].firstName", "firstName")]
    [InlineData("personalInfoNav[0].lastName", "lastName")]
    [InlineData("personalInfoNav[0].preferredName", "preferredName")]
    [InlineData("personalInfoNav[0].displayName", "displayName")]
    [InlineData("emailNav[0].emailAddress", "email")]
    [InlineData("emailNav[?(@.isPrimary == true)].emailAddress", "email")]
    [InlineData("emailNav[?(@.isPrimary == true)].emailType", "emailType")]
    [InlineData("emailNav[?(@.isPrimary == true)].isPrimary", "emailIsPrimary")]
    [InlineData("employmentNav[0].startDate", "startDate")]
    [InlineData("employmentNav[0].jobInfoNav[0].department", "department")]
    [InlineData("employmentNav[0].jobInfoNav[0].departmentNav.department", "department")]
    [InlineData("employmentNav[0].jobInfoNav[0].departmentNav.name_localized", "department")]
    [InlineData("employmentNav[0].jobInfoNav[0].departmentNav.name", "department")]
    [InlineData("employmentNav[0].jobInfoNav[0].company", "company")]
    [InlineData("employmentNav[0].jobInfoNav[0].companyNav.company", "company")]
    [InlineData("employmentNav[0].jobInfoNav[0].companyNav.name_localized", "company")]
    [InlineData("employmentNav[0].jobInfoNav[0].location", "location")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.LocationName", "location")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.name", "location")]
    [InlineData("employmentNav[0].jobInfoNav[0].jobTitle", "jobTitle")]
    [InlineData("employmentNav[0].jobInfoNav[0].businessUnit", "businessUnit")]
    [InlineData("employmentNav[0].jobInfoNav[0].businessUnitNav.businessUnit", "businessUnit")]
    [InlineData("employmentNav[0].jobInfoNav[0].businessUnitNav.name_localized", "businessUnit")]
    [InlineData("employmentNav[0].jobInfoNav[0].division", "division")]
    [InlineData("employmentNav[0].jobInfoNav[0].divisionNav.division", "division")]
    [InlineData("employmentNav[0].jobInfoNav[0].divisionNav.name_localized", "division")]
    [InlineData("employmentNav[0].jobInfoNav[0].costCenter", "costCenter")]
    [InlineData("employmentNav[0].jobInfoNav[0].costCenterNav.costCenterDescription", "costCenter")]
    [InlineData("employmentNav[0].jobInfoNav[0].costCenterNav.name_localized", "costCenter")]
    [InlineData("employmentNav[0].jobInfoNav[0].costCenterNav.description_localized", "costCenterDescription")]
    [InlineData("employmentNav[0].jobInfoNav[0].costCenterNav.externalCode", "costCenterId")]
    [InlineData("employmentNav[0].jobInfoNav[0].employeeClass", "employeeClass")]
    [InlineData("employmentNav[0].jobInfoNav[0].employeeType", "employeeType")]
    [InlineData("employmentNav[0].jobInfoNav[0].emplStatus", "emplStatus")]
    [InlineData("employmentNav/jobInfoNav/emplStatus", "emplStatus")]
    [InlineData("employmentNav[0].jobInfoNav[0].employeeStatus", "employeeStatus")]
    [InlineData("employmentNav/jobInfoNav/employeeStatus", "employeeStatus")]
    [InlineData("employmentNav[0].jobInfoNav[0].employeestatus", "employeestatus")]
    [InlineData("employmentNav/jobInfoNav/employeestatus", "employeestatus")]
    [InlineData("employmentNav[0].jobInfoNav[0].managerId", "managerId")]
    [InlineData("employmentNav[0].userNav.manager.empInfo.personIdExternal", "managerId")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString3", "peopleGroup")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString20", "leadershipLevel")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString87", "region")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString110", "geozone")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString111", "bargainingUnit")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString91", "unionJobCode")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString112", "cintasUniformCategory")]
    [InlineData("employmentNav[0].jobInfoNav[0].customString113", "cintasUniformAllotment")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.addressNavDEFLT.address1", "officeLocationAddress")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.addressNavDEFLT.city", "officeLocationCity")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.addressNavDEFLT.zipCode", "officeLocationZipCode")]
    [InlineData("employmentNav[0].jobInfoNav[0].locationNav.addressNavDEFLT.customString4", "officeLocationCustomString4")]
    [InlineData("employmentNav[0].jobInfoNav[0].companyNav.externalCode", "companyId")]
    [InlineData("employmentNav[0].jobInfoNav[0].businessUnitNav.externalCode", "businessUnitId")]
    [InlineData("employmentNav[0].jobInfoNav[0].divisionNav.externalCode", "divisionId")]
    [InlineData("employmentNav[0].jobInfoNav[0].departmentNav.externalCode", "departmentId")]
    [InlineData("employmentNav[0].jobInfoNav[0].jobCodeNav.name_localized", "jobCode")]
    [InlineData("employmentNav[0].jobInfoNav[0].jobCodeNav.externalCode", "jobCodeId")]
    [InlineData("employmentNav[0].jobInfoNav[0].payGradeNav.name", "payGrade")]
    [InlineData("employmentNav[0].jobInfoNav[0].position", "position")]
    [InlineData("customNav[0].customField", "customNav[0].customField")]
    public void Normalize_MapsKnownSuccessFactorsPaths(string source, string expected)
    {
        Assert.Equal(expected, SourceAttributePathNormalizer.Normalize(source));
    }
}
