<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\SyncFactors.Domain\SyncFactors.Domain.csproj" />
    <ProjectReference Include="..\..\src\SyncFactors.Contracts\SyncFactors.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
