<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SyncFactors.Infrastructure\SyncFactors.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SyncFactors.MockSuccessFactors\SyncFactors.MockSuccessFactors.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
