sonar.projectName=syncfactors
sonar.sourceEncoding=UTF-8
sonar.sources=src,scripts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ps1
sonar.exclusions=.github/**,artifacts/**,config/**,tests/**,.tools/**
sonar.coverage.exclusions=tests/**,.github/**,config/**,.tools/**
sonar.coverage.jacoco.xmlReportPaths=artifacts/coverage.xml
