using SyncFactors.Domain;

namespace SyncFactors.MockSuccessFactors;

internal readonly record struct MockNameProfile(
    string FirstName,
    string LastName,
    string? PreferredName)
{
    public string DisplayName => $"{PreferredName ?? FirstName} {LastName}".Trim();
}

internal static class MockNameCatalog
{
    private static readonly GivenName[] GivenNames =
    [
        new("Abigail", "Abby"),
        new("Adrian", "Adrian"),
        new("Aiden", "Aiden"),
        new("Aisha", "Aisha"),
        new("Alexandra", "Alex"),
        new("Alyssa", "Alyssa"),
        new("Amelia", "Mia"),
        new("Andre", "Andre"),
        new("Ariana", "Ari"),
        new("Audrey", "Audrey"),
        new("Avery", "Avery"),
        new("Benjamin", "Ben"),
        new("Bianca", "Bianca"),
        new("Blake", "Blake"),
        new("Brandon", "Brandon"),
        new("Brianna", "Bri"),
        new("Caleb", "Caleb"),
        new("Camila", "Cami"),
        new("Cameron", "Cam"),
        new("Caroline", "Carrie"),
        new("Carter", "Carter"),
        new("Charlotte", "Charlie"),
        new("Chloe", "Chloe"),
        new("Christian", "Chris"),
        new("Claire", "Claire"),
        new("Cole", "Cole"),
        new("Connor", "Connor"),
        new("Daniel", "Dan"),
        new("Delaney", "Lane"),
        new("Dominic", "Dom"),
        new("Eleanor", "Ellie"),
        new("Elena", "Elena"),
        new("Elijah", "Eli"),
        new("Elizabeth", "Liz"),
        new("Ella", "Ella"),
        new("Emily", "Em"),
        new("Ethan", "Ethan"),
        new("Eva", "Eva"),
        new("Evelyn", "Evie"),
        new("Gabriel", "Gabe"),
        new("Genesis", "Gen"),
        new("Gianna", "Gia"),
        new("Grace", "Grace"),
        new("Graham", "Graham"),
        new("Hannah", "Hannah"),
        new("Harper", "Harper"),
        new("Hazel", "Hazel"),
        new("Henry", "Henry"),
        new("Hudson", "Hud"),
        new("Ian", "Ian"),
        new("Isaac", "Isaac"),
        new("Isabella", "Bella"),
        new("Jack", "Jack"),
        new("Jackson", "Jax"),
        new("Jacob", "Jake"),
        new("Jasmine", "Jasmine"),
        new("Javier", "Javi"),
        new("Jayden", "Jay"),
        new("Josephine", "Josie"),
        new("Julian", "Jules"),
        new("Katherine", "Kate"),
        new("Kennedy", "Kennedy"),
        new("Landon", "Landon"),
        new("Layla", "Layla"),
        new("Leah", "Leah"),
        new("Leo", "Leo"),
        new("Lillian", "Lily"),
        new("Luca", "Luca"),
        new("Lucy", "Lucy"),
        new("Madeline", "Maddie"),
        new("Marcus", "Marc"),
        new("Mason", "Mase"),
        new("Maya", "Maya"),
        new("Mia", "Mia"),
        new("Miles", "Miles"),
        new("Natalie", "Nat"),
        new("Nathan", "Nate"),
        new("Nora", "Nora"),
        new("Noah", "Noah"),
        new("Oliver", "Ollie"),
        new("Olivia", "Liv"),
        new("Owen", "Owen"),
        new("Paisley", "Paisley"),
        new("Penelope", "Penny"),
        new("Piper", "Piper"),
        new("Quinn", "Quinn"),
        new("Riley", "Riley"),
        new("Roman", "Roman"),
        new("Ruby", "Ruby"),
        new("Sadie", "Sadie"),
        new("Samuel", "Sam"),
        new("Scarlett", "Scout"),
        new("Sebastian", "Seb"),
        new("Skylar", "Sky"),
        new("Sofia", "Sofi"),
        new("Stella", "Stella"),
        new("Theodore", "Theo"),
        new("Thomas", "Tom"),
        new("Victoria", "Tori"),
        new("William", "Will"),
        new("Zoe", "Zoe")
    ];

    private static readonly string[] LastNames =
    [
        "Adams",
        "Allen",
        "Alvarez",
        "Anderson",
        "Armstrong",
        "Bailey",
        "Baker",
        "Barnes",
        "Bell",
        "Bennett",
        "Brooks",
        "Bryant",
        "Butler",
        "Campbell",
        "Carter",
        "Castillo",
        "Chavez",
        "Clark",
        "Coleman",
        "Collins",
        "Cook",
        "Cooper",
        "Cox",
        "Cruz",
        "Davis",
        "Diaz",
        "Edwards",
        "Evans",
        "Fisher",
        "Flores",
        "Foster",
        "Garcia",
        "Gomez",
        "Gonzalez",
        "Gray",
        "Green",
        "Griffin",
        "Hall",
        "Harris",
        "Hayes",
        "Henderson",
        "Hill",
        "Howard",
        "Hughes",
        "Jackson",
        "James",
        "Jenkins",
        "Johnson",
        "Kelly",
        "King",
        "Lee",
        "Lewis",
        "Long",
        "Lopez",
        "Martin",
        "Martinez",
        "Miller",
        "Mitchell",
        "Moore",
        "Morgan",
        "Morris",
        "Murphy",
        "Nelson",
        "Nguyen",
        "Ortiz",
        "Parker",
        "Patel",
        "Perez",
        "Perry",
        "Peterson",
        "Powell",
        "Price",
        "Ramirez",
        "Reed",
        "Reyes",
        "Richardson",
        "Rivera",
        "Roberts",
        "Robinson",
        "Rodriguez",
        "Rogers",
        "Ross",
        "Russell",
        "Sanders",
        "Scott",
        "Simmons",
        "Smith",
        "Stewart",
        "Taylor",
        "Thomas",
        "Thompson",
        "Torres",
        "Turner",
        "Walker",
        "Ward",
        "Watson",
        "White",
        "Williams",
        "Wilson",
        "Wood",
        "Wright",
        "Young"
    ];

    public static MockNameProfile GetNameProfile(int sequence, bool includePreferredName)
    {
        var normalizedSequence = unchecked((uint)sequence);
        var givenNameIndex = (int)(normalizedSequence % (uint)GivenNames.Length);
        var lastNameIndex = (int)((normalizedSequence / (uint)GivenNames.Length) % (uint)LastNames.Length);
        var givenName = GivenNames[givenNameIndex];

        return new MockNameProfile(
            FirstName: givenName.FirstName,
            LastName: LastNames[lastNameIndex],
            PreferredName: includePreferredName ? givenName.PreferredName : null);
    }

    public static string BuildEmailLocalPart(string firstName, string lastName)
        => DirectoryIdentityFormatter.BuildBaseEmailLocalPart(firstName, lastName);

    public static string BuildEmailAddress(string firstName, string lastName, string domain = "example.test")
        => DirectoryIdentityFormatter.BuildEmailAddress(BuildEmailLocalPart(firstName, lastName), domain);

    private readonly record struct GivenName(string FirstName, string PreferredName);
}
